# see http://jekyllrb.com/docs/configuration/#default-configuration
title: A Java Developer's Weblog
email:
description: Java development, continuous integration, stuff.
baseurl: ""
url: "https://martoe.github.io"
twitter_username: martin_ehr
github_username:  martoe

kramdown:
  input: GFM
